version: 2
jobs:
  build_windows:
    docker:
      - image: linuturk/mono-choco
    steps:
      - checkout
#      - run:
#          name: Create NuGet
#          command: npm install && grunt windows
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential libssl-dev curl
            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            apt-get install -y nodejs
            npm install grunt nexe
      - run:
          name: Do Grunt
          command: /usr/bin/grunt windows
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
