version: 2
jobs:
  build_windows:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
#      - run:
#          name: Create NuGet
#          command: npm install && grunt windows
      - run:
          name: Install Mono
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            sudo apt install apt-transport-https
            echo "deb https://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            sudo apt update
            sudo apt install mono-devel
      - run:
          name: Do Grunt
          command: npm install && grunt windows
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
