version: 2
jobs:
  build_windows:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install AWS CLI, Grunt CLI, and NEXE
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python-dev python3-dev \
              build-essential libssl-dev libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev python-pip
            sudo pip install --upgrade pip
            sudo pip install awscli
            sudo npm install -g nexe grunt-cli
      - run:
          name: Do Gruntfile Steps
          command: |
            nexe -i index.js -o logdna.exe -f -t ~/tmp -r 8.11.3
            cat package.json | grep "version" | cut -d':' -f2 | cut -d'"' -f2 >> VERSION.txt
            cp LICENSE.md LICENSE.txt
            mkdir -p .builds/windows/tools/
            cp VERSION.txt LICENSE.txt logdna.exe .builds/windows/tools
            cp logdna.nuspec .builds/windows
            zip -r logdna.1.3.0.zip .builds/windows
            aws s3 cp logdna.1.3.0.zip s3://repo.logdna.com/win/logdna.1.3.0.zip
  push_to_choco:
    docker:
      - image: linuturk/mono-choco
    steps:
      - checkout
      - run:
          name: Install WGet, UnZip
          command: |
            lsb_release -a
            apt-get update
            apt-get install -y wget unzip
      - run:
          name: Create NuPkg and Update
          command: |
            wget https://s3.amazonaws.com/repo.logdna.com/win/logdna.1.3.0.zip
            unzip logdna.1.3.0.zip && cd .builds/windows
            sed -i 's/tools\\/tools\//g' logdna.nuspec
            choco pack logdna.nuspec 2>/dev/null
            choco push logdna.1.3.0.nupkg -k="${CHOCO_API_KEY}" --source https://push.chocolatey.org/api/v2/package 2>/dev/null
workflows:
  version: 2
  build_and_deploy:
    jobs:
#      - build_windows:
#          filters:
#            branches:
#              only: Configs
#              ignore:
#                - master
#                - Updates
      - push_to_choco:
#          requires:
#            - build_windows
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
