version: 2
jobs:
  build_windows:
    docker:
      - image: linuturk/mono-choco
    steps:
      - checkout
#      - run:
#          name: Create NuGet
#          command: npm install && grunt windows
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential libssl-dev curl
            curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
      - run:
          name: Install NuGet
          command: |
            chmod +x ~/.nvm/nvm.sh
            ~/.nvm/nvm.sh install v8.11.3
            ~/.nvm/nvm.sh use v8.11.3
            npm install --global grunt nexe
            choco -?
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
