version: 2
jobs:
  build_windows:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
#      - run:
#          name: Create NuGet
#          command: npm install && grunt windows
      - run:
          name: Install Mono
          command: |
            cat /etc/os-release
            lsb_release -a
            hostnamectl
            uname -r
      - run:
          name: Do Grunt
          command: npm install && grunt windows
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
