version: 2
jobs:
  build_windows:
    docker:
      - image: linuturk/mono-choco
      - image: circleci/node:8
    steps:
      - checkout
#      - run:
#          name: Create NuGet
#          command: npm install && grunt windows
      - run:
          name: Install NuGet
          command: choco install logdna-cli
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
