version: 2
jobs:
  build_windows:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Debian Version
          command: cat /etc/os-release
      - run:
          name: Install Mono
          command: |
            sudo apt-get install apt-transport-https -y
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            echo "deb https://download.mono-project.com/repo/debian stable-jessie/snapshots/4.0.1 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
            sudo apt-get update
            sudo apt-get install mono-devel -y
            mono --version
      - run:
          name: Install Chocolatey
          command: |
            git clone https://github.com/chocolatey/choco.git
            cd choco && git checkout stable
            export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig:/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig:$PKG_CONFIG_PATH
            chmod +x build.sh
            chmod +x zip.sh
            ./build.sh
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install python3 python-dev python3-dev \
              build-essential libssl-dev libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev python-pip
            sudo pip install --upgrade pip
            sudo pip install awscli
      - run:
          name: Install .NET
          command: |
            sudo apt-get install -y apt-transport-https
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
            sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
            wget -q https://packages.microsoft.com/config/debian/8/prod.list
            sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
            sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
            sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-2.1
      - run:
          name: Install Grunt CLI and NEXE
          command: |
            sudo npm install -g nexe grunt-cli
            npm install && grunt circle_windows
      - run:
          name: Upload NuPKG into Choco
          command: |
            curl --insecure -X PUT -H "X-NuGet-ApiKey: ${CHOCO_API_KEY}" -T "./.builds/windows/bin/Debug/logdna.1.3.0.nupkg" "https://push.chocolatey.org/api/v2/package"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
