version: 2
jobs:
  build_windows:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install .NET
          command: |
            sudo apt-get install -y apt-transport-https
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
            sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
            wget -q https://packages.microsoft.com/config/debian/8/prod.list
            sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
            sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
            sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-2.1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_windows:
          filters:
            branches:
              only: Configs
              ignore:
                - master
                - Updates
